name: Compile Assets (Vite)
on: [push, pull_request]
jobs:
  build-assets:
    strategy:
      matrix:
        operating-system:
          - ubuntu-24.04
        php-version:
          - '8.3.7'
    name: ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP 8.3.7
        uses: shivammathur/setup-php@v3
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, dom, gd, libxml, mbstring, zip, mysql, xml, intl, bcmath, redis-phpredis/phpredis@6.0.1
          ini-values: error_reporting=E_ALL
          coverage: pcov
          tools: composer:v4
        env:
          REDIS_CONFIGURE_OPTS: --enable-redis
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Specific NPM Version
        run: npm install -g npm@latest
      - name: Install Composer Dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
      - name: Install JS Dependencies
        run: npm install
      - name: Compile Assets (Vite)
        run: npm run build
